import "../styles/globals.css"
import { MoralisProvider } from "react-moralis"
import { NotificationProvider } from "@web3uikit/core"
import { Header } from "@/components/header"
import Head from "next/head"
import { Navbar } from "@/components/navbar"

export default function App({ Component, pageProps }) {
    return (
        <div className="bg-indigo-800 h-full min-h-screen">
            <Head>
                <title>Ridlearn</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <NotificationProvider>
                    <Header />
                    <Component {...pageProps} />
                    <div className="h-20"></div>
                    <Navbar />
                </NotificationProvider>
            </MoralisProvider>
        </div>
    )
}
